<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\EU.Core.Agent.Application\EU.Core.Agent.Application.csproj" />
    <ProjectReference Include="..\EU.Core.Agent.Runtime\EU.Core.Agent.Runtime.csproj" />
    <ProjectReference Include="..\EU.Core.Agent.Infrastructure\EU.Core.Agent.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
</Project>
