<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\common.targets" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EU.Core.Agent.Application\EU.Core.Agent.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="ModelContextProtocol" Version="1.4.1" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <PackageReference Include="sqlSugarCore" Version="5.1.4.213-preview05" />
  </ItemGroup>
</Project>
