<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\build\common.targets" />

  <ItemGroup>
    <ProjectReference Include="..\EU.Core.Model\EU.Core.Model.csproj" />
    <ProjectReference Include="..\Src\EU.Core.Common\EU.Core.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EM\" />
    <Folder Include="IDS4Db\" />
    <Folder Include="IV\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
  </ItemGroup>

</Project>
