-- Add table and business-column comments for normalized MCP storage. MySQL 8.0.13+.

ALTER TABLE `AgMcpServerDefinition` COMMENT = 'MCP Server 定义主表',
    MODIFY `Id` CHAR(36) NOT NULL COMMENT '主键',
    MODIFY `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    MODIFY `IsActive` TINYINT(1) NULL DEFAULT 1 COMMENT '基础启用标记',
    MODIFY `ImportDataId` CHAR(36) NULL COMMENT '导入数据标识',
    MODIFY `ModificationNum` INT NULL DEFAULT 0 COMMENT '修改次数',
    MODIFY `Tag` INT NULL DEFAULT 1 COMMENT '通用标签',
    MODIFY `GroupId` CHAR(36) NULL COMMENT '集团标识',
    MODIFY `CompanyId` CHAR(36) NULL COMMENT '公司标识',
    MODIFY `AuditStatus` VARCHAR(32) NULL DEFAULT 'Add' COMMENT '审核状态',
    MODIFY `CurrentNode` VARCHAR(32) NULL COMMENT '当前流程节点',
    MODIFY `CreatedBy` CHAR(36) NULL COMMENT '创建人',
    MODIFY `CreatedTime` DATETIME NULL COMMENT '创建时间',
    MODIFY `UpdateBy` CHAR(36) NULL COMMENT '更新人',
    MODIFY `UpdateTime` DATETIME NULL COMMENT '更新时间',
    MODIFY `Code` VARCHAR(128) NOT NULL COMMENT 'MCP Server 唯一编码',
    MODIFY `Name` VARCHAR(256) NOT NULL COMMENT 'MCP Server 显示名称',
    MODIFY `Description` LONGTEXT NOT NULL COMMENT 'MCP Server 说明',
    MODIFY `Transport` VARCHAR(32) NOT NULL COMMENT '传输类型',
    MODIFY `Endpoint` VARCHAR(2048) NOT NULL COMMENT 'HTTP 或 SSE 端点',
    MODIFY `Command` VARCHAR(512) NOT NULL COMMENT 'Stdio 启动命令',
    MODIFY `CredentialAlias` VARCHAR(200) NOT NULL COMMENT '凭据别名',
    MODIFY `Enabled` TINYINT(1) NOT NULL COMMENT '是否启用',
    MODIFY `LogicalRevision` BIGINT NOT NULL COMMENT '逻辑修订号',
    MODIFY `Status` VARCHAR(32) NOT NULL COMMENT '生命周期与同步状态',
    MODIFY `LastError` VARCHAR(4096) NOT NULL COMMENT '最近同步错误',
    MODIFY `LastSyncedAtUtc` DATETIME(6) NULL COMMENT '最近同步 UTC 时间';

ALTER TABLE `AgMcpServerArgument` COMMENT = 'MCP Server Stdio 参数表',
    MODIFY `ID` CHAR(36) NOT NULL COMMENT '主键',
    MODIFY `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    MODIFY `IsActive` TINYINT(1) NULL DEFAULT 1 COMMENT '基础启用标记',
    MODIFY `ImportDataId` CHAR(36) NULL COMMENT '导入数据标识',
    MODIFY `ModificationNum` INT NULL DEFAULT 0 COMMENT '修改次数',
    MODIFY `Tag` INT NULL DEFAULT 1 COMMENT '通用标签',
    MODIFY `GroupId` CHAR(36) NULL COMMENT '集团标识',
    MODIFY `CompanyId` CHAR(36) NULL COMMENT '公司标识',
    MODIFY `AuditStatus` VARCHAR(32) NULL DEFAULT 'Add' COMMENT '审核状态',
    MODIFY `CurrentNode` VARCHAR(32) NULL COMMENT '当前流程节点',
    MODIFY `CreatedBy` CHAR(36) NULL COMMENT '创建人',
    MODIFY `CreatedTime` DATETIME NULL COMMENT '创建时间',
    MODIFY `UpdateBy` CHAR(36) NULL COMMENT '更新人',
    MODIFY `UpdateTime` DATETIME NULL COMMENT '更新时间',
    MODIFY `ServerId` CHAR(36) NOT NULL COMMENT '所属 MCP Server 主键',
    MODIFY `Ordinal` INT NOT NULL COMMENT '参数排列顺序',
    MODIFY `Value` VARCHAR(1024) NOT NULL COMMENT '参数值';

ALTER TABLE `AgMcpToolVersion` COMMENT = 'MCP 工具不可变版本历史表',
    MODIFY `ID` CHAR(36) NOT NULL COMMENT '工具版本主键',
    MODIFY `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记',
    MODIFY `IsActive` TINYINT(1) NULL DEFAULT 1 COMMENT '基础启用标记',
    MODIFY `ImportDataId` CHAR(36) NULL COMMENT '导入数据标识',
    MODIFY `ModificationNum` INT NULL DEFAULT 0 COMMENT '修改次数',
    MODIFY `Tag` INT NULL DEFAULT 1 COMMENT '通用标签',
    MODIFY `GroupId` CHAR(36) NULL COMMENT '集团标识',
    MODIFY `CompanyId` CHAR(36) NULL COMMENT '公司标识',
    MODIFY `AuditStatus` VARCHAR(32) NULL DEFAULT 'Add' COMMENT '审核状态',
    MODIFY `CurrentNode` VARCHAR(32) NULL COMMENT '当前流程节点',
    MODIFY `CreatedBy` CHAR(36) NULL COMMENT '创建人',
    MODIFY `CreatedTime` DATETIME NULL COMMENT '创建时间',
    MODIFY `UpdateBy` CHAR(36) NULL COMMENT '更新人',
    MODIFY `UpdateTime` DATETIME NULL COMMENT '更新时间',
    MODIFY `ServerId` CHAR(36) NOT NULL COMMENT '所属 MCP Server 主键',
    MODIFY `HistoryOrdinal` INT NOT NULL COMMENT '历史版本排列顺序',
    MODIFY `CurrentOrdinal` INT NULL COMMENT '当前工具排列顺序；历史版本为空',
    MODIFY `Name` VARCHAR(256) NOT NULL COMMENT '工具名称',
    MODIFY `Description` VARCHAR(4096) NOT NULL COMMENT '工具说明',
    MODIFY `InputSchemaJson` LONGTEXT NOT NULL COMMENT '工具输入 JSON Schema',
    MODIFY `Risk` VARCHAR(32) NOT NULL COMMENT '工具风险等级',
    MODIFY `Sha256` CHAR(64) NOT NULL COMMENT '工具版本 SHA-256 摘要',
    MODIFY `DiscoveredAtUtc` DATETIME(6) NOT NULL COMMENT '发现 UTC 时间';
