<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\build\common.targets" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EU.Core.Services\EU.Core.Services.csproj" />
    <ProjectReference Include="..\Src\EU.Core.Extensions\EU.Core.Extensions.csproj" />
    <ProjectReference Include="..\Src\EU.Core.Tasks\EU.Core.Tasks.csproj" />
  </ItemGroup>

</Project>
