-- Operator-owned SQL Server placeholder for P5 Agent runtime audit.
-- The independent Host uses local SQLite and never executes this file.
-- Table names and fields remain operator-owned until the SQL Server merge phase.
