global using System.Data;
global using System.Dynamic;
global using System.Linq.Expressions;
global using System.Text;
global using System.Text.RegularExpressions;
global using EU.Core.Api.Filter;
global using EU.Core.Common;
global using EU.Core.Common.Enums;
global using EU.Core.Common.Helper;
global using EU.Core.Common.HttpContextUser;
global using EU.Core.Common.LogHelper;
global using EU.Core.Common.Module;
global using EU.Core.Model.Entity;
global using EU.Core.Controllers;
global using EU.Core.DataAccess;
global using EU.Core.Domain;
global using EU.Core.IServices;
global using EU.Core.Model;
global using EU.Core.Model.Models;
global using EU.Core.Model.Edit;
global using EU.Core.Model.Insert;
global using EU.Core.Model.ViewModels;
global using EU.Core.Repository.UnitOfWorks;
global using EU.Core.SwaggerHelper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Newtonsoft.Json;
global using static EU.Core.Extensions.SwaggerSetup;
global using DbInsert = EU.Core.Common.DbInsert;
global using DbUpdate = EU.Core.Common.DbUpdate;
global using DBHelper = EU.Core.Common.Helper.DBHelper;
