<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EU.Core.Agent.Api\EU.Core.Agent.Api.csproj" />
    <ProjectReference Include="..\..\src\EU.Core.Agent.Application\EU.Core.Agent.Application.csproj" />
    <ProjectReference Include="..\..\src\EU.Core.Agent.Runtime\EU.Core.Agent.Runtime.csproj" />
    <ProjectReference Include="..\..\src\EU.Core.Agent.Infrastructure\EU.Core.Agent.Infrastructure.csproj" />
  </ItemGroup>
</Project>
